package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Thursday, March 22, 2018 2:36:22 PM IST
*/

public interface HelloOperations 
{
  String sayHello ();
  void shutdown ();
} // interface HelloOperations
